apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: db-backup
spec:
  # Backup the database every day at 1AM
  schedule: "00 01 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: db-backup
            image: postgres:9.6
            command: ["/bin/sh"]
            args: ["-c", 'echo "$PGPASS" > /root/.pgpass && chmod 600 /root/.pgpass && pg_dumpall -U <dbuser> -h <dbhost>  > /var/backups/db-backup-$(date +"%d-%m-%Y-%H-%M").bak && echo done']
            env:
            - name: PGPASS
              valueFrom:
                secretKeyRef:
                  name: pgpass
                  key: pgpass
            volumeMounts:
            - mountPath: /var/backups
              name: postgres-backup
          
          containers:
          - name: copy-s3
            image: giddy87/giddy-repo:kops
            command: ["/bin/sh"]
            args: ["-c", "echo copy start && aws s3 mv /var/backups/. s3://<your bucket> --recursive && echo done "]
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: aws_access_key_id                                                                                                                                                                               
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: aws_default_region
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: aws_secret_access_key
            volumeMounts:
            - mountPath: /var/backups
              name: postgres-backup



          restartPolicy: Never
          volumes:
          - name: postgres-backup
            hostPath:
              path: /var/volumes/postgres-backups
              type: DirectoryOrCreate

           
